### ISSUE TITLE
Android Studio 4.2 canary 10 Preview Render Problem: java.lang.AssertionError: Unsupported Service: activity

### ISSUE THREAD

**Issue by mr3y-the-programmer** [chrisbanes/accompanist#100]
Whenever you use `@Composable CoilImage()` or `@Composable CoilImageWithCrossfade(),` Compose `@Preview` shows a rendering problem saying:
```
java.lang.AssertionError: Unsupported Service: activity
	at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:669)
	at android.content.Context.getSystemService(Context.java:3705)
	at androidx.core.content.ContextCompat.getSystemService(ContextCompat.java:716)
	at coil.util.Utils.getDefaultAvailableMemoryPercentage(Utils.kt:86)
	at coil.ImageLoader$Builder.<init>(ImageLoader.kt:109)
	at coil.ImageLoader$Companion.create(ImageLoader.kt:449)
	at coil.Coil.newImageLoader(Coil.kt:77)
	at coil.Coil.imageLoader(Coil.kt:24)
	at dev.chrisbanes.accompanist.coil.CoilImage__CoilKt.CoilImage(Coil.kt:84)
	at dev.chrisbanes.accompanist.coil.CoilImage.CoilImage(CoilImage>)
	at com.example.jetsnack.ui.components.SnacksKt$SnackImage$1.invoke(Snacks.kt:262)
	at com.example.jetsnack.ui.components.SnacksKt$SnackImage$1.invoke(Snacks.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at com.example.jetsnack.ui.components.SurfaceKt$JetsnackSurface$1.invoke(Surface.kt:62)
	at com.example.jetsnack.ui.components.SurfaceKt$JetsnackSurface$1.invoke(Surface.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.foundation.BoxKt.Box-mP80RHo(Box.kt:109)
	at com.example.jetsnack.ui.components.SurfaceKt.JetsnackSurface-biUpMIw(Surface.kt:52)
	at com.example.jetsnack.ui.components.SnacksKt.SnackImage-SPfEvbc(Snacks.kt:256)
	at com.example.jetsnack.ui.components.SnacksKt$SnackItem$1.invoke(Snacks.kt:169)
	at com.example.jetsnack.ui.components.SnacksKt$SnackItem$1.invoke(Snacks.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at com.example.jetsnack.ui.components.SurfaceKt$JetsnackSurface$1.invoke(Surface.kt:62)
	at com.example.jetsnack.ui.components.SurfaceKt$JetsnackSurface$1.invoke(Surface.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.foundation.BoxKt.Box-mP80RHo(Box.kt:109)
	at com.example.jetsnack.ui.components.SurfaceKt.JetsnackSurface-biUpMIw(Surface.kt:52)
	at com.example.jetsnack.ui.components.SnacksKt.SnackItem(Snacks.kt:159)
	at com.example.jetsnack.ui.components.SnacksKt$Snacks$1.invoke(Snacks.kt:147)
	at com.example.jetsnack.ui.components.SnacksKt$Snacks$1.invoke(Snacks.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:151)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.foundation.ScrollKt.ScrollableRow(Scroll.kt:511)
	at com.example.jetsnack.ui.components.SnacksKt.Snacks(Snacks.kt:144)
	at com.example.jetsnack.ui.components.SnacksKt.SnackCollection(Snacks.kt:105)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt$Body$1$1$1.invoke(SnackDetail.kt:194)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt$Body$1$1$1.invoke(SnackDetail.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at com.example.jetsnack.ui.components.SurfaceKt$JetsnackSurface$1.invoke(Surface.kt:62)
	at com.example.jetsnack.ui.components.SurfaceKt$JetsnackSurface$1.invoke(Surface.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.foundation.BoxKt.Box-mP80RHo(Box.kt:109)
	at com.example.jetsnack.ui.components.SurfaceKt.JetsnackSurface-biUpMIw(Surface.kt:52)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt$Body$1$1.invoke(SnackDetail.kt:154)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt$Body$1$1.invoke(SnackDetail.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:151)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.foundation.ScrollKt.ScrollableColumn(Scroll.kt:462)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt.Body(SnackDetail.kt:152)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt.access$Body(SnackDetail.kt)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt$SnackDetail$1.invoke(SnackDetail.kt:102)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt$SnackDetail$1.invoke(SnackDetail.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:151)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.foundation.layout.StackKt$Stack$stackChildren$1.invoke(Stack.kt:54)
	at androidx.compose.foundation.layout.StackKt$Stack$stackChildren$1.invoke(Stack.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.ui.LayoutKt.Layout(Layout.kt:675)
	at androidx.compose.foundation.layout.StackKt.Stack(Stack.kt:56)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt.SnackDetail(SnackDetail.kt:99)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt$SnackDetailDarkPreview$1.invoke(SnackDetail.kt:369)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt$SnackDetailDarkPreview$1.invoke(SnackDetail.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at androidx.compose.foundation.TextKt.ProvideTextStyle(Text.kt:241)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:71)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:65)
	at com.example.jetsnack.ui.theme.ThemeKt$JetsnackTheme$2.invoke(Theme.kt:95)
	at com.example.jetsnack.ui.theme.ThemeKt$JetsnackTheme$2.invoke(Theme.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at com.example.jetsnack.ui.theme.ThemeKt.ProvideJetsnackColors(Theme.kt:228)
	at com.example.jetsnack.ui.theme.ThemeKt.JetsnackTheme(Theme.kt:94)
	at com.example.jetsnack.ui.snackdetail.SnackDetailKt.SnackDetailDarkPreview(SnackDetail.kt:368)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at androidx.ui.tooling.preview.PreviewUtilsKt.invokeComposableMethod(PreviewUtils.kt:141)
	at androidx.ui.tooling.preview.PreviewUtilsKt.invokeComposableViaReflection(PreviewUtils.kt:180)
	at androidx.ui.tooling.preview.ComposeViewAdapter$init$1$1$composable$1.invoke(ComposeViewAdapter.kt:371)
	at androidx.ui.tooling.preview.ComposeViewAdapter$init$1$1$composable$1.invoke(ComposeViewAdapter.kt)
	at androidx.ui.tooling.preview.ComposeViewAdapter$init$1$1.invoke(ComposeViewAdapter.kt:403)
	at androidx.ui.tooling.preview.ComposeViewAdapter$init$1$1.invoke(ComposeViewAdapter.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at androidx.ui.tooling.InspectableKt.Inspectable(Inspectable.kt:62)
	at androidx.ui.tooling.preview.ComposeViewAdapter$WrapPreview$1.invoke(ComposeViewAdapter.kt:328)
	at androidx.ui.tooling.preview.ComposeViewAdapter$WrapPreview$1.invoke(ComposeViewAdapter.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at androidx.ui.tooling.preview.ComposeViewAdapter.WrapPreview(ComposeViewAdapter.kt:327)
	at androidx.ui.tooling.preview.ComposeViewAdapter.access$WrapPreview(ComposeViewAdapter.kt)
	at androidx.ui.tooling.preview.ComposeViewAdapter$init$1.invoke(ComposeViewAdapter.kt:364)
	at androidx.ui.tooling.preview.ComposeViewAdapter$init$1.invoke(ComposeViewAdapter.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.ui.selection.SelectionContainerKt$SelectionContainer$3$1.invoke(SelectionContainer.kt:88)
	at androidx.compose.ui.selection.SelectionContainerKt$SelectionContainer$3$1.invoke(SelectionContainer.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.ui.LayoutKt.Layout(Layout.kt:675)
	at androidx.compose.ui.selection.SelectionLayoutKt.SelectionLayout(SelectionLayout.kt:80)
	at androidx.compose.ui.selection.SelectionContainerKt$SelectionContainer$3.invoke(SelectionContainer.kt:85)
	at androidx.compose.ui.selection.SelectionContainerKt$SelectionContainer$3.invoke(SelectionContainer.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at androidx.compose.ui.selection.SelectionContainerKt.SelectionContainer(SelectionContainer.kt:82)
	at androidx.compose.ui.selection.SelectionContainerKt.SelectionContainer(SelectionContainer.kt:39)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$1$1.invoke(Wrapper.kt:274)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$1$1.invoke(Wrapper.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at androidx.compose.ui.platform.AmbientsKt.ProvideCommonAmbients(Ambients.kt:109)
	at androidx.compose.ui.platform.AndroidAmbientsKt$ProvideAndroidAmbients$3.invoke(AndroidAmbients.kt:101)
	at androidx.compose.ui.platform.AndroidAmbientsKt$ProvideAndroidAmbients$3.invoke(AndroidAmbients.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at androidx.compose.ui.platform.AndroidAmbientsKt.ProvideAndroidAmbients(AndroidAmbients.kt:93)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$1.invoke(Wrapper.kt:273)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$1.invoke(Wrapper.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.kt:272)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:2686)
	at androidx.compose.runtime.Composer.composeInitial(Composer.kt:1853)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:241)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:110)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt:264)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.kt:557)
	at android.view.View.dispatchAttachedToWindow(View.java:20479)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:44)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:354)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:435)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:141)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:704)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$6(RenderTask.java:859)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$2.run(RenderExecutor.kt:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This stacktrace from [Jetsnack](https://github.com/android/compose-samples/tree/master/Jetsnack) sample app, but also I wrote some compose code for [Sunflower](https://github.com/android/sunflower) and encountered the same issue

**Comment by nickbutcher** [comment]
Looks like it's not finding a `Context` which we added for the [imageLoader default param](https://github.com/chrisbanes/accompanist/pull/80).

**Comment by chrisbanes** [comment]
It's getting a context, but it's the special layoutlib `com.android.layoutlib.bridge.android.BridgeContext`, which doesn't seem to support `getSystemService(ActivityManager)`. Coil [uses](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/util/Utils.kt#L53) it find to determine the cache size.

/cc @colinrtwhite

**Comment by mr3y-the-programmer** [comment]
Yeah! that makes sense because it works at runtime when you have an activity instance running so you have a valid Context, But as I said you can't use it in any `@Preview` function at compile time because there is no way to get a context

**Comment by colinrtwhite** [comment]
Thanks for the heads up! I think https://github.com/coil-kt/coil/pull/541 should fix the issue.

**Comment by chrisbanes** [comment]
Thanks @colinrtwhite 🙌

**Comment by mr3y-the-programmer** [comment]
Thanks, @colinrtwhite, @chrisbanes preview no longer complains with the release of v0.3.0 which fixes the issue

**Comment by chrisbanes** [comment]
Interesting! We haven't updated to the new (upcoming) Coil with the fix yet. Maybe Android Studio 4.2.0 C13 has a fix in it? Either way, glad it's fixed
