### ISSUE TITLE
[Glide] Compose version 1.0.0-beta01 : java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by open-schnick** [chrisbanes/accompanist#212]
When bumping up to the beta of compose that came out yesterday, `GlideImage` breaks the app.
Stacktrace:

```
  Process: <package_name>, PID: 8990
  java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/ui/platform/AndroidAmbientsKt;
      at dev.chrisbanes.accompanist.glide.GlideImageDefaults.defaultRequestManager(GlideImage.kt:77)
      at dev.chrisbanes.accompanist.glide.GlideImage__GlideImageKt.GlideImage(GlideImage.kt:189)
      at dev.chrisbanes.accompanist.glide.GlideImage.GlideImage(GlideImage.kt:1)
     ...
```
# Versions:

- kotlin version: 1.4.30
- compose 1.0.0-beta01
```
dependencies {

    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui-tooling:$compose_version"
    implementation "androidx.compose.runtime:runtime:$compose_version"
    implementation "androidx.compose.runtime:runtime-livedata:$compose_version"
    implementation "androidx.activity:activity-compose:1.3.0-alpha03"
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.0'
    implementation 'androidx.room:room-runtime:2.2.6'
    implementation "androidx.compose.material:material-icons-extended:$compose_version"
    //noinspection GradleDynamicVersion
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    // Room dependency
    def room_version = "2.2.6"
    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"

    // logging
    implementation 'com.jakewharton.timber:timber:4.7.1'

    // serializing
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1'

    // coroutines for getting off the UI thread
    def coroutines = "1.4.2"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutines"

    implementation "dev.chrisbanes.accompanist:accompanist-glide:0.5.1"

    // navigation
    // https://maven.google.com/web/index.html?q=androidx.nav#androidx.navigation:navigation-compose
    implementation "androidx.navigation:navigation-compose:1.0.0-alpha08"
}
```

**Comment by open-schnick** [comment]
I am using the following code:
```
GlideImage(
    data = TemplateHandler.getTemplateById(deeplink.createdByTemplateId).previewImageResource,
    modifier = modifier,
    contentDescription = null
)
```

**Comment by open-schnick** [comment]
Works after bumping up to v 0.6.0. Thanks for the fast reaction

**Comment by chrisbanes** [comment]
Each Accompanist release works with a specific Compose version. For `1.0.0-beta01` you should use Accompanist `0.6.0` https://github.com/chrisbanes/accompanist/releases/tag/v0.6.0

Thanks,
Chris
________________________________
